export type RootStackParamList = {
    Main: undefined;
    BSMain: undefined;
    Invitation: undefined;
    Auth: undefined;
    BabyIndi: undefined;
    Register: undefined;
    SetInfoParent: undefined;
    EditInfoParent: undefined;
    DisplayInfoParent: undefined;
    SetInfoBS: undefined;
    EditInfoBS: undefined;
    DisplayInfoBS: undefined;
    WorkDiary: undefined;
    MainParent: undefined;
    BabyDiary: undefined;
    Calendar: undefined;
    Chatting: undefined;
    Camera: undefined;
};